window.translations = {
    en: {
        hello: "Hello, I am",
        buildingRobust: "Building",
        robustSystems: "Robust Systems",
        ampersand: "&",
        intuitiveInterfaces: "Intuitive Interfaces",
        subtitle: "Software Engineer & Full-Stack Developer specializing in Laravel, Modern Web Technologies, and AI Integration.",
        viewProjects: "View Projects",
        aboutMe: "About Me",
        bridging: "Bridging the gap between Design and Engineering.",
        description: "I am a Software Engineer with a strong foundation in <strong>Full-Stack Web Development</strong>. Currently active as a Freelance IT Consultant, I help businesses transform their ideas into scalable digital products.",
        techStack: "Tech Stack",
        itSolutions: "IT Solutions Provider",
        endToEnd: "End-to-End Digital Transformation",
        msibLabel: "MSIB",
        microsoftAlumni: "Microsoft Alumni",
        featuredProjects: "Featured Projects",
        scrollDown: "Scroll down to see my recent work",
        b2bTitle: "B2B Supply Chain System",
        b2bDesc: "Full-featured B2B platform with supplier dashboard, order management, automated pricing, and delivery tracking system.",
        govtRoomTitle: "Govt. Room Booking",
        govtRoomDesc: "Internal reservation system for Dinas Pendidikan. Features conflict detection and automated scheduling.",
        chessSchoolTitle: "Chess School Web",
        chessSchoolDesc: "Modern profile website for Wonosobo Chess School. Focused on SEO and accessibility.",
        eduCenterTitle: "Edu Center Platform",
        eduCenterDesc: "Conversion-focused landing page for a Tutoring Agency, highlighting courses and success stories.",
        aiStoryTitle: "AI Story Generator",
        aiStoryDesc: "Generates creative stories instantly using Groq AI. Showcasing prompt engineering.",
        footageTitle: "Auto Footage Finder",
        footageDesc: "Tool for content creators to fetch stock videos by keyword using Pixabay API.",
        sportHubTitle: "Sport Hub UI",
        sportHubDesc: "Mobile app design for finding sports partners. Includes prototyping and user journey.",
        letsBuild: "Let's Build Something Amazing Together",
        openFor: "Currently open for freelance projects and full-time opportunities.",
        whatsappBtn: "Chat on WhatsApp",
        emailBtn: "Send Email",
        copyright: "© 2026 Ahmad Sultoni Alwi. Built with Tailwind CSS & Swiper."
    },
    id: {
        hello: "Halo, saya adalah",
        buildingRobust: "Membangun",
        robustSystems: "Sistem Handal",
        ampersand: "&",
        intuitiveInterfaces: "Antarmuka Intuitif",
        subtitle: "Software Engineer & Full-Stack Developer yang berspesialisasi dalam Laravel, Teknologi Web Modern, dan Integrasi AI.",
        viewProjects: "Lihat Proyek",
        aboutMe: "Tentang Saya",
        bridging: "Menjembatani celah antara Desain dan Engineering.",
        description: "Saya adalah Software Engineer dengan fondasi kuat dalam Full-Stack Web Development. Saat ini aktif sebagai Freelance IT Consultant, membantu bisnis mengubah ide mereka menjadi produk digital yang scalable.",
        techStack: "Tech Stack",
        itSolutions: "Penyedia Solusi IT",
        endToEnd: "Transformasi Digital End-to-End",
        msibLabel: "MSIB",
        microsoftAlumni: "Alumni Microsoft",
        featuredProjects: "Proyek Unggulan",
        scrollDown: "Scroll ke bawah untuk melihat pekerjaan terbaru saya",
        b2bTitle: "Sistem Supply Chain B2B",
        b2bDesc: "Platform B2B lengkap dengan dashboard supplier, manajemen pesanan, penetapan harga otomatis, dan sistem pelacakan pengiriman.",
        govtRoomTitle: "Sistem Booking Ruang Pemerintah",
        govtRoomDesc: "Sistem reservasi internal untuk Dinas Pendidikan. Dilengkapi deteksi konflik dan penjadwalan otomatis.",
        chessSchoolTitle: "Website Sekolah Catur",
        chessSchoolDesc: "Website profil modern untuk Sekolah Catur Wonosobo. Fokus pada SEO dan aksesibilitas.",
        eduCenterTitle: "Platform Pusat Pendidikan",
        eduCenterDesc: "Landing page fokus konversi untuk Agensi Bimbingan Belajar, menampilkan kursus dan kisah sukses.",
        aiStoryTitle: "Pembuat Cerita AI",
        aiStoryDesc: "Menghasilkan cerita kreatif secara instan menggunakan Groq AI. Menampilkan prompt engineering.",
        footageTitle: "Pencari Footage Otomatis",
        footageDesc: "Tool untuk content creator mengambil video stok berdasarkan keyword menggunakan Pixabay API.",
        sportHubTitle: "Sport Hub UI",
        sportHubDesc: "Desain aplikasi mobile untuk mencari mitra olahraga. Mencakup prototyping dan user journey.",
        letsBuild: "Mari Kita Bangun Sesuatu yang Luar Biasa Bersama",
        openFor: "Saat ini terbuka untuk proyek freelance dan peluang full-time.",
        whatsappBtn: "Chat di WhatsApp",
        emailBtn: "Kirim Email",
        copyright: "© 2026 Ahmad Sultoni Alwi. Dibuat dengan Tailwind CSS & Swiper."
    }
};
